### ISSUE TITLE
Bug ao consultar o histório de um dispositivo.

### ISSUE THREAD

**Issue by leocesartavares** [dojot/history#35]
Utilizei o Docker Compose para montar a plataforma em uma máquina, criei um template e posteriormente criei um device. Até aí tudo bem, consegui persistir informações e consultar o histórico. O problema começou quando alterei um template: modifiquei o nome de parâmetros, excluí alguns e criei outros. A partir daí a consulta ao histórico parou de funcionar para os itens novos. Eu então excluí o device, o template e criei tudo de novo e o histórico não funcionou.

**Comment by giovannicuriel** [comment]
Boa tarde! O problema que você descreveu parece bastante com o dojot/dojot#828, que foi corrigido no #32. Só para garantir que este é o caso mesmo, você poderia testar com esta descrição do `persister` no seu docker-compose?

```yaml
  persister:
    image: dojot/persister:latest
    restart: always
    depends_on:
      - mongodb
      - auth
      - kafka
      - data-broker
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_MANAGEMENT_USER: 'persister'
      DOJOT_MANAGEMENT_TENANT: 'internal'
      KAFKA_GROUP_ID: 'persister-group'
    logging:
      driver: json-file
      options:
        max-size: 100m
```

Só para informação: esta descrição usa uma versão que possui vários bugfixes desde a versão de setembro/2018 (e algumas alterações na configuração).
